name: On commit v1

on:
  push:
jobs:
  Run_tests:
    name: Run unit test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Remove package-lock
      run: rm -rf package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run es-lint
    - name: Run unit test
      run: npm test
